export const GET_REG_SUCCESS: 'GET_REG_SUCCESS' = 'GET_REG_SUCCESS';
export const GET_REG_FAILED: 'GET_REG_FAILED' = 'GET_REG_FAILED';

export const GET_AUTH_SUCCESS:  'GET_AUTH_SUCCESS' = 'GET_AUTH_SUCCESS';
export const GET_AUTH_FAILED: 'GET_AUTH_FAILED' = 'GET_AUTH_FAILED';

export const RESTORE_USER_SUCCESS: 'RESTORE_USER_SUCCESS' = 'RESTORE_USER_SUCCESS';
export const RESTORE_USER_FAILED: 'RESTORE_USER_FAILED' = 'RESTORE_USER_FAILED';

export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';