export const FORGOT_SUCCESS: 'FORGOT_SUCCESS' = 'FORGOT_SUCCESS';
export const FORGOT_FAILED: 'FORGOT_FAILED' = 'FORGOT_FAILED';

export const RESET_SUCCESS: 'RESET_SUCCESS' = 'RESET_SUCCESS';
export const RESET_FAILED:'RESET_FAILED' = 'RESET_FAILED';

export const CLEAR_RESET_PASSWORD: 'CLEAR_RESET_PASSWORD' = 'CLEAR_RESET_PASSWORD';