export const SEND_ORDER_SUCCESS:'SEND_ORDER_SUCCESS' = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_REQUEST:'SEND_ORDER_REQUEST' = 'SEND_ORDER_REQUEST';
export const SEND_ORDER_FAILED:'SEND_ORDER_FAILED' = 'SEND_ORDER_FAILED';
export const CONFIRM_ORDER:'CONFIRM_ORDER' = 'CONFIRM_ORDER';

export const GET_ORDER_SUCCESS:'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_FAILED:'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';